language: python
python:
  - "2.7"

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=pep8

install:
  - "pip install tox"

script:
  - "./run_tests.sh -N --no-pep8"

notifications:
  slack: bebaproj:QOVWgAeMr7r6YebwBWwApXea
  email: false